### ISSUE TITLE
Logs not being received on Heroku

### ISSUE THREAD

**Issue by diefer91** [SwiftyBeaver/SwiftyBeaver-Vapor#10]
I am successfully getting my Vapor app logs through the Mac App running locally, but when I deploy to Heroku I am not receiving any logs. I thought it was because I had the free version of SwiftyBeaver, so I upgrade to the paid version, but still no logs. Would appreciate your help, thanks!

**Comment by blazierkyle** [comment]
+1 I'm having this same issue

**Comment by skreutzberger** [comment]
Hi, I don’t know the reason but it may be that Heroku has a more restrictive file system which does not allow the storing of the temporary log buffer files?

**Comment by blazierkyle** [comment]
Thanks for the response. Will anyone from the SwiftyBeaver team be looking into this issue? I know that Heroku is a very popular deployment platform for Vapor apps.

**Comment by skreutzberger** [comment]
Yes, we will investigate it further.
