### ISSUE TITLE
Unable to specify config for Swift v4.x

### ISSUE THREAD

**Issue by MartinW** [SwiftyBeaver/SwiftyBeaver-Vapor#18]
A Swift 5 dependency has been introduced with FilterValidator.swift. 

Flexible config is required for Vapor installs still using Swift 4.x versions.

**Comment by skreutzberger** [comment]
Good point! Can you submit a PR which fixes the issue?

**Comment by hungri-yeti** [comment]
I (not OP) have submitted a PR #20 for this.
